name: Deploy Marketing App To Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - auth/**
      - .github/workflows/azure-blob-storage-marketing.yml
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          npm install
          npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./auth/dist

  download-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-upload]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./production-files

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_AUTH_CONTAINER: ${{ secrets.AZURE_STORAGE_AUTH_CONTAINER }}
        with:
          azcliversion: 2.28.0
          inlineScript: |
            az storage blob upload-batch --destination $AZURE_STORAGE_AUTH_CONTAINER --source ./production-files --connection-string $AZURE_STORAGE_CONNECTION_STRING

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        env:
          CDN_PROFILE_NAME: ${{ secrets.CDN_PROFILE_NAME }}
          CDN_ENDPOINT: ${{ secrets.CDN_ENDPOINT }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name $CDN_PROFILE_NAME --name $CDN_ENDPOINT --resource-group $RESOURCE_GROUP

      - name: Azure logout
        run: |
          az logout
        shell: bash
