name: Upload To Azure Blob Storage

on:
  push:
    branches:
      - main
    paths:
      - marketing/**
      - .github/workflows/azure-blob-storage-upload-marketing.yml
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marketing
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: |
          npm install
          npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./marketing/dist

  download-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-upload]
    defaults:
      run:
        working-directory: marketing

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./production-files

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.28.0
          inlineScript: |
            az storage blob upload-batch --account-name mdmicrofe --destination https://mdmicrofe.blob.core.windows.net/marketing --source ./production-files --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

      - name: Azure logout
        run: |
          az logout
