name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main
    paths:
      - marketing/**
      - .github/workflows/azure-blob-storage-upload-marketing.yml
jobs:
  build:
    runs-on: ubuntu-latest

  build-and-upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marketing
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build

      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: dist
          container_name: marketing
          connection_string: ${{ secrets.ConnectionString }}
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: "true"
